FROM python:3.10-slim

WORKDIR /app

COPY . .

COPY ../scripts /scripts  

RUN apt-get update && apt-get install -y git && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]