FROM python:3.10-slim

WORKDIR /app

COPY . .

COPY ../scripts /scripts  

RUN apt-get update && apt-get install -y git
RUN apt-get update && apt-get install -y docker.io docker-compose
RUN pip install -r requirements.txt

CMD ["python", "backend/app.py"]